### ISSUE TITLE
Some commands are not being imported

### ISSUE THREAD

**Issue by onedr0p** [p3lim/vyaml#2]
Looks like some set commands are not being added in the `render` command the one thing I think these all have in common is the look like this in the yaml

### Yaml

```yaml
system:
  config-management:
    commit-revisions: '100'
  conntrack:
    modules: # anything with empty {} doesn't render
      ftp: {}
      h323: {}
      nfs: {}
      pptp: {}
      sip: {}
      sqlnet: {}
      tftp: {}
```

### Set commands

```
set firewall name wan-servers enable-default-log
set firewall zone local local-zone
set interfaces loopback lo
set nat destination rule 400 disable
set service dhcp-server shared-network-name GUEST authoritative
set service dhcp-server shared-network-name GUEST ping-check
set service dns forwarding name-server 1.0.0.1
set service dns forwarding name-server 1.1.1.1
set service dns forwarding name-server 8.8.4.4
set service dns forwarding name-server 8.8.8.8
set service ntp server 0.us.pool.ntp.org
set service ntp server 1.us.pool.ntp.org
set service ntp server 2.us.pool.ntp.org
set service ntp server 3.us.pool.ntp.org
set service ssh disable-password-authentication
set system conntrack modules ftp
set system conntrack modules h323
set system conntrack modules nfs
set system conntrack modules pptp
set system conntrack modules sip
set system conntrack modules sqlnet
set system conntrack modules tftp
set system ipv6 disable-forwarding
set system logs logrotate messages
set system option reboot-on-panic
set system option startup-beep
set system syslog host 192.168.42.201 format octet-counted
```

**Comment by onedr0p** [comment]
I take it some of these need to be arrays but I am not sure how that would work on commands like this:

```yaml
      LAN:
        authoritative: {}
        ping-check: {}
        subnet:
          192.168.0.0/24:
            default-router: 192.168.0.1
            domain-name: turbo.ac
```
