### ISSUE TITLE
Add support for !include directive

### ISSUE THREAD

**Issue by bjw-s** [p3lim/vyaml#3]
It would be awesome if you could add support for an `!include` directive so that the configuration file can be split up in to multiple files.

### Example:

`config.yaml`:
```yaml
system:
  host-name: vyos
  name-server:
    - 1.1.1.1
    - 1.0.0.1

container: !include container.yaml
firewall: !include firewall.yaml
```

`container.yaml`:
```yaml
name:
  nginx:
    port:
      http:
        source: 80
        destination: 80
```
