### ISSUE TITLE
Enhance YAML overrides

### ISSUE THREAD

**Issue by onedr0p** [p3lim/vyaml#5]
It would be nice to have a way to define common values with a dot prefix

```yaml
.container: &container
  memory: '0'
  shared-memory: '0'

container:
  name:
    bind:
      <<: *container
      cap-add: ["net-bind-service"]
      command: /usr/sbin/named -4 -f -c /etc/bind/named.conf -u bind
      image: docker.io/internetsystemsconsortium/bind9:9.19
      network containers address: ["192.168.254.10"]
```
